name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello World
        run: echo "Hello World !!"
      - name: Display GoodBye
        run: echo "Done - GoodBye !!"
