name: First WorkFlow
on:
  workflow_dispatch:
    inputs:
      label:
        description: "Text to be shown"
        default: 'Hello'
        required: true
        type: string
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello World
        run: |
          echo "Hello World !!"
          echo "Done - GoodBye !!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Label Input Data
        run: |
          echo "Label Input: ${{ inputs.label }}"
