name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello World
        run: |
          echo "Hello World !!"
          echo "Done - GoodBye !!"
